require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

install! 'cocoapods',
  :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
end

target 'App' do
  capacitor_pods

  post_install do |installer|
    assertDeploymentTarget(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # For Xcode 15.3 (macOS-14)
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'

        if config.name.include?('Debug')
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        else
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        end

        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['DEVELOPMENT_TEAM'] = ''
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        config.build_settings['PROVISIONING_PROFILE'] = ''
      end
    end
  end
end