require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

install! 'cocoapods',
  :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
end

target 'App' do
  capacitor_pods

  post_install do |installer|
    # Apply to BOTH the main project AND the Pods project
    [installer.pods_project, installer.project].each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          # CRITICAL: Set Swift version for ALL targets
          config.build_settings['SWIFT_VERSION'] = '5.0'

          # Fix optimization level
          if config.name.include?('Debug')
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
          else
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
          end

          # Set deployment target
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

          # Enable modules
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

          # Disable code signing for Pods
          if target.respond_to?(:product_type) && target.product_type == 'framework'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['DEVELOPMENT_TEAM'] = ''
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
            config.build_settings['PROVISIONING_PROFILE'] = ''
          end
        end
      end
    end
  end
end